// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApRZaURh2oxJYaMX0QXDwvoFzm0k6vvwE',
    appId: '1:75969579081:web:d1cb99905544ff7f4d1798',
    messagingSenderId: '75969579081',
    projectId: 'gold-18f36',
    authDomain: 'gold-18f36.firebaseapp.com',
    storageBucket: 'gold-18f36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTLVWCO1w2CdX-IMPKUhi_fp-OHW7sO2s',
    appId: '1:75969579081:android:64e0f0dc6b7f23ad4d1798',
    messagingSenderId: '75969579081',
    projectId: 'gold-18f36',
    storageBucket: 'gold-18f36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2YtiCA7PY_gcdjgZ8qsf8284bfwiVUYM',
    appId: '1:75969579081:ios:7695e65438d2e4524d1798',
    messagingSenderId: '75969579081',
    projectId: 'gold-18f36',
    storageBucket: 'gold-18f36.appspot.com',
    iosClientId: '75969579081-vjh679bcge7k9s3q8ciiudu48s79vj2u.apps.googleusercontent.com',
    iosBundleId: 'com.deniz.gold.denizGold',
  );
}
